config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "search#index"

  # advanced forms
  match "journals/advanced", to: "journals_advanced#index", as: "journals_advanced_search", via: [:get, :post]
  match "databases/advanced", to: "databases_advanced#index", as: "databases_advanced_search", via: [:get, :post]
  match "articles/advanced", to: "primo_advanced#index", as: "articles_advanced_search", via: [:get, :post]
  match "catalog/advanced", to: "advanced#index", as: "advanced_search", via: [:get, :post]
  match "catalog/:id/purchase_order", to: "catalog#purchase_order_action", via: [:post], as: "purchase_order_action"

  # concerns
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  # mounts
  mount Blacklight::Engine => "/"
  mount BlacklightAdvancedSearch::Engine => "/"
  mount BentoSearch::Engine => "/bento"

  get "books/:id", to: redirect { |_, req| req.url.sub("books", "catalog") }
  get "books", to: redirect { |_, req|
    redirect_path = req.url.sub("books", "catalog")

    if req.params.empty?
      redirect_path += "?f[format][]=Book"
    elsif !req.params.dig("f", "format")&.include?("Book")
      redirect_path += "&f[format][]=Book"
    end

    redirect_path
  }


  # resource and resources
  resource :catalog, only: [:index], as: "catalog", path: "/catalog", controller: "catalog" do
    concerns :searchable
    concerns :range_searchable
  end

  resource :journals, only: [:index], as: "journals", path: "/journals", controller: "journals" do
    concerns :searchable
    concerns :range_searchable
  end

  resource :databases, only: [:index], as: "databases", path: "/databases", controller: "databases" do
    concerns :searchable
    concerns :range_searchable
  end

  resources :solr_documents, only: [:show], path: "/catalog", controller: "catalog" do
    concerns :exportable
  end

  resources :solr_journal_documents, only: [:show], path: "/journals", controller: "journals" do
    concerns :exportable
  end

  resources :solr_database_documents, only: [:show], path: "/databases", controller: "databases" do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete "clear"
    end
  end

  resources :primo_central_documents, only: [:show], path: "/articles", controller: "primo_central" do
    concerns :exportable
  end

  post "catalog/:id/track" => "catalog#track"
  post "articles/:id/track" => "primo_central#track", as: :track_primo_central
  post "journals/:id/track" => "journal#track"
  post "databases/:id/track" => "databases#track"

  devise_for :users, controllers: { sessions: "sessions", omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get "alma/social_login_callback" => "sessions#social_login_callback"
  end

  # auth
  authenticate do
    post "users/renew"

    get "users/account"

    get "users/fines", as: "user_fines"

    get "users/holds", as: "user_holds"

    get "users/loans", as: "user_loans"

    post "users/renew_selected"

    post "users/renew_all"

  end

  # gets
  get "bento" => "search#index", :as => "multi_search"
  get "everything" => "search#index", :as => "everything"
  get "catalog/:id/staff_view", to: "catalog#librarian_view", as: "staff_view"
  get "articles_advanced", to: "primo_advanced#index", as: "legacy_articles_advanced_search"

  get "catalog/:id/index_item", to: "catalog#index_item", as: "index_item"
  get "journals/:id/index_item", to: "journals#index_item", as: "journal_item"
  get "databases/:id/index_item", to: "databases#index_item", as: "database_item"
  get "articles/:id/index_item", to: "primo_central#index_item", as: "articles_index_item"
  get "catalog/:id/purchase_order", to: "catalog#purchase_order", as: "purchase_order"


  #
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  # we want helper methods for multi_search_path and multi_search_url
  # too, without removing root_url and root_path helpers. oddly, repeating
  # root seems to work.

  get "almaws/item/:mms_id", to:  "almaws#item", as: "item"
  get "almaws/request/:mms_id/:pickup_location/:request_level", to: "almaws#request_options", as: "request_options"
  post "almaws/request/digitization", to: "almaws#send_digitization_request", as: "digitization_request"
  post "almaws/request/hold", to: "almaws#send_hold_request", as: "hold_request"
  post "almaws/request/booking", to: "almaws#send_booking_request", as: "booking_request"

  scope module: "blacklight_alma" do
    get "alma/availability" => "alma#availability"
  end


  # matches
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/articles", to: "primo_central#index", as: "search", via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/search/solr/response.rb
# frozen_string_literal: true

module Search::Solr
  class Response < Blacklight::Solr::Response
    def merge_facet(name:, value:, hits: nil)
      if self.dig("facet_counts", "facet_fields", name)
        # We need to sort on merge or facet item always appends to list.
        config = blacklight_config&.facet_fields || {}

        sort_proc = config.dig(name, "sort_proc") ||
          -> (f) { (v, _) = f; v.titleize }

        merged = Hash[*facet_fields[name]]
          .merge(value => hits).sort_by(&sort_proc)
          .to_a.flatten

        self["facet_counts"]["facet_fields"][name] = merged
      else
        self["facet_counts"]["facet_fields"][name] = [ value, hits ]
      end
    end
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < CatalogController
  include CatalogConfigReinit

  blacklight_config.configure do |config|
    config.add_search_field "all_fields", label: "All Fields"
    config.response_model = Search::Solr::Response

    config.add_index_field "format", label: "Resource Type", raw: true, helper_method: :index_translate_resource_type_code, no_label: true
    config.add_facet_field "format", label: "Resource Type", url_method: :path_for_books_and_media_facet, helper_method: :translate_resource_type_code, show: true, limit: -1
  end

  def index
    @per_page = 3
    if params[:q]
      engines = %i(books_and_media articles databases journals cdm)
      searcher = BentoSearch::ConcurrentSearcher.new(*engines)
      searcher.search(params[:q], per_page: @per_page, semantic_search_field: params[:field])
      @results = process_results(searcher.results)
    end

    respond_to do |format|
      format.html { store_preferred_view }
      format.json do
        @response ||= Blacklight::PrimoCentral::Response.new({})
        @results ||= []
        @presenter = Blacklight::JsonPresenter.new(@response,
                                                   @results,
                                                   [],
                                                   blacklight_config)
      end
    end
  end

  private
    def process_results(results)
      # We only care about cdm results count not bento box.
      cdm_total_items = results["cdm"]&.total_items

      unless results["books_and_media"].blank?
        items = results["books_and_media"][0...-1]
        items.engine_id = results["books_and_media"].engine_id
        items.total_items = results["books_and_media"].total_items
        items.display_configuration = results["books_and_media"].display_configuration

        # Grabbing and setting @response in order to render facets.
        # Merges cdm totals into the @response.
        @response = results["books_and_media"].last.custom_data
        @response.merge_facet(name: "format", value: "digital_collections", hits: cdm_total_items)

        results.merge(
          "books_and_media" => items,
          ).except("cdm")
      else
        results.except("cdm")
      end
    end
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
  ##
  # Links More bento block facet back to catalog or content DM link.
  # @param [Blacklight::Solr::Response::Facets::FacetField] facet_field
  # @param [String] item
  # @return [String]
  def path_for_books_and_media_facet(facet_field, item)
    if item.value == "digital_collections"
      "https://digital.library.temple.edu/digital/search/searchterm/#{params[:q]}/order/nosort"
    else
      search_catalog_url(search_state.add_facet_params_and_redirect(facet_field, item))
    end
  end

  def renderable_results(results = @results, options = {})
    results.select { |engine_id, result| render_search?(result, options) }
  end

  def render_search?(result, options = {})
    id = result.engine_id
    !(["more", "resource_types"].include?(id) &&
       total_items(result) == 0) &&
    !(is_child_box?(id) && !options[:render_child_box])
  end

  def bento_titleize(id)
    engine = BentoSearch.get_engine(id)
    if id == "books_and_media"
      link_to "Books & Media", engine.url(self), id: "bento_" + id
    else
      link_to id.titleize , engine.url(self), id: "bento_" + id
    end
  end

  def render_bento_results(results = @results, options = {})
    results_class = options[:results_class] || "d-md-flex flex-wrap"
    comp_class = options[:comp_class] || "bento_compartment p-2 mt-4 mr-4"

    render partial: "bento_results", locals: {
      results_class: results_class,
      comp_class: comp_class,
      results: results, options: options }
  end

  def render_linked_results(engine_id)
    engine_ids = engine_display_configurations[engine_id][:linked_engines] || [] rescue []
    results = @results.select { |id, result| engine_ids.include? id }
    render_bento_results(results, render_child_box: true, results_class: "bento_results", comp_class: "bento_compartment")
  end

  def is_child_box?(id)
    linked_engines.include? id
  end

  def linked_engines
    engine_display_configurations.select { |id, config| config[:linked_engines] }
      .map { |id, config| config[:linked_engines] }
      .flatten
  end

  def engine_display_configurations
    @engine_configurations ||= @results.map   { |engine_id, result|
      config = BentoSearch.get_engine(engine_id).configuration[:for_display]
      [engine_id, config]
    }.to_h
  end
end

app/views/search/_bento_availability.html.erb
<% if has_one_electronic_resource?(item.custom_data) %>
  <%= link_to "Online", bento_single_link(item.custom_data["electronic_resource_display"]), class:"btn btn-xs bento-avail-btn", title:"This link opens the resource in a new tab.", target:"_blank" %>
<% elsif has_many_electronic_resources?(item.custom_data) %>
  <%= link_to "Online", solr_document_url(item.custom_data["id"]), class:"btn btn-xs bento-avail-btn", title:"This link opens the resource in a new tab.", target:"_blank" %>
<% end %>

app/views/search/_bento_results.html.erb
<div class="<%= results_class %> masonry px-3">
  <% renderable_results(results, options).each_pair do |engine_id, result| %>
    <div class="mx-auto test <%= comp_class %> <%= engine_id %>">
      <h2 class="rounded-top m-0"><%= bento_icons(engine_id) %><%= bento_titleize(engine_id) %> </h2>
      <%= render :layout => "layouts/bento_box_wrapper", :locals => {:results => result } do %>
        <%= bento_search result %>
      <% end %>
      <%= render_linked_results(engine_id) %>
    </div>
  <% end %>
</div>

app/views/search/_blacklight_availability.html.erb
<% if has_one_electronic_resource?(item.custom_data) %>
  <%= link_to "Online", bento_single_link(item.custom_data["electronic_resource_display"]), class:"btn btn-sm bento-avail-btn mt-1", title:"This link opens the resource in a new tab.", target:"_blank", id: "one_online_button" %>
<% elsif has_many_electronic_resources?(item.custom_data) %>
  <%= link_to "Online", solr_document_url(item.custom_data["id"]), class:"btn btn-sm bento-avail-btn mt-1", id: "many_online_button" %>
<% end %>

app/views/search/_facet_layout.html.erb
    <div class="panel-body">
      <%= yield %>
    </div>

app/views/search/_home_text.html.erb
<div id="getting-started">
  <p class="section-heading"><%= t("bento.section_heading_html",
    articles: link_to(t("bento.articles"), search_path, class: "text-red"),
    journals: link_to(t("bento.journals"), search_journals_path, class: "text-red"),
    databases: link_to(t("bento.databases"), search_journals_path, class: "text-red"),
    more: link_to(t("bento.more"), search_databases_path, class: "text-red")) %></p>

  <p class="section-heading"><strong><%= t("bento.library_search_question") %></strong></p>
  <p><%= t("bento.library_search_answer") %></p>

  <p><%= t("bento.need_help_html") %></p>
  <p><%= t("bento.library_help_html", href: link_to(t("blacklight.help_href"), t("blacklight.help_link"))) %></p>

  <p><%= t("bento.more_information_html") %></p>
  <p><%= t("bento.more_information_answer_html", href: faq_link(:long)) %></p>

</div>

app/views/search/_primo_availability.html.erb
<%= bento_availability(item.custom_data) %>

app/views/search/_resource_types.html.erb
<% format_facet = @response.aggregations["format"] %>

<div class="bg-white p-4">
  <div class="bento-resource-container">
    <h2 class="bento-resource-types pb-3 border-bottom border-red"><%= t("bento.resource_types_header") %></h2>
    <ul class="pt-2 m-0 pl-0 list-inline d-flex flex-wrap justify-content-start">
      <% format_facet.items.each do |item| -%>
        <li class="bento-resource-list-item list-inline-item pb-1"><%= render_bento_format_facet_value(item) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/search/_suggestions.html.erb
<h5><%= t("no_results.header") %></h5>
<ul class="pb-4">
  <li><%= t("no_results.modify_words") %></li>
  <li><%= t("no_results.fewer_keywords") %></li>
  <li><%= t("no_results.spell_check") %></li>
  <li>
    <%= help_link %>
    <%= t("no_results.for_help") %>
  </li>
</ul>

app/views/search/index.html.erb
<% if @results %>
  <div class="bento-container pt-2 pb-5">
    <%= render_bento_results %>
  </div>
  <%= render :partial => "resource_types" %>
<% else %>
  <div class="bento-container">
    <%= render("home_text") %>
  </div>
<% end %>