config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "search#index"

  # advanced forms
  match "journals/advanced", to: "journals_advanced#index", as: "journals_advanced_search", via: [:get, :post]
  match "databases/advanced", to: "databases_advanced#index", as: "databases_advanced_search", via: [:get, :post]
  match "articles/advanced", to: "primo_advanced#index", as: "articles_advanced_search", via: [:get, :post]
  match "catalog/advanced", to: "advanced#index", as: "advanced_search", via: [:get, :post]
  match "catalog/:id/purchase_order", to: "catalog#purchase_order_action", via: [:post], as: "purchase_order_action"

  # concerns
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  # mounts
  mount Blacklight::Engine => "/"
  mount BlacklightAdvancedSearch::Engine => "/"
  mount BentoSearch::Engine => "/bento"

  get "books/:id", to: redirect { |_, req| req.url.sub("books", "catalog") }
  get "books", to: redirect { |_, req|
    redirect_path = req.url.sub("books", "catalog")

    if req.params.empty?
      redirect_path += "?f[format][]=Book"
    elsif !req.params.dig("f", "format")&.include?("Book")
      redirect_path += "&f[format][]=Book"
    end

    redirect_path
  }


  # resource and resources
  resource :catalog, only: [:index], as: "catalog", path: "/catalog", controller: "catalog" do
    concerns :searchable
    concerns :range_searchable
  end

  resource :journals, only: [:index], as: "journals", path: "/journals", controller: "journals" do
    concerns :searchable
    concerns :range_searchable
  end

  resource :databases, only: [:index], as: "databases", path: "/databases", controller: "databases" do
    concerns :searchable
    concerns :range_searchable
  end

  resources :solr_documents, only: [:show], path: "/catalog", controller: "catalog" do
    concerns :exportable
  end

  resources :solr_journal_documents, only: [:show], path: "/journals", controller: "journals" do
    concerns :exportable
  end

  resources :solr_database_documents, only: [:show], path: "/databases", controller: "databases" do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete "clear"
    end
  end

  resources :primo_central_documents, only: [:show], path: "/articles", controller: "primo_central" do
    concerns :exportable
  end

  post "catalog/:id/track" => "catalog#track"
  post "articles/:id/track" => "primo_central#track", as: :track_primo_central
  post "journals/:id/track" => "journal#track"
  post "databases/:id/track" => "databases#track"

  devise_for :users, controllers: { sessions: "sessions", omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get "alma/social_login_callback" => "sessions#social_login_callback"
  end

  # auth
  authenticate do
    post "users/renew"

    get "users/account"

    get "users/fines", as: "user_fines"

    get "users/holds", as: "user_holds"

    get "users/loans", as: "user_loans"

    post "users/renew_selected"

    post "users/renew_all"

  end

  # gets
  get "bento" => "search#index", :as => "multi_search"
  get "everything" => "search#index", :as => "everything"
  get "catalog/:id/staff_view", to: "catalog#librarian_view", as: "staff_view"
  get "articles_advanced", to: "primo_advanced#index", as: "legacy_articles_advanced_search"

  get "catalog/:id/index_item", to: "catalog#index_item", as: "index_item"
  get "journals/:id/index_item", to: "journals#index_item", as: "journal_item"
  get "databases/:id/index_item", to: "databases#index_item", as: "database_item"
  get "articles/:id/index_item", to: "primo_central#index_item", as: "articles_index_item"
  get "catalog/:id/purchase_order", to: "catalog#purchase_order", as: "purchase_order"


  #
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  # we want helper methods for multi_search_path and multi_search_url
  # too, without removing root_url and root_path helpers. oddly, repeating
  # root seems to work.

  get "almaws/item/:mms_id", to:  "almaws#item", as: "item"
  get "almaws/request/:mms_id/:pickup_location/:request_level", to: "almaws#request_options", as: "request_options"
  post "almaws/request/digitization", to: "almaws#send_digitization_request", as: "digitization_request"
  post "almaws/request/hold", to: "almaws#send_hold_request", as: "hold_request"
  post "almaws/request/booking", to: "almaws#send_booking_request", as: "booking_request"

  scope module: "blacklight_alma" do
    get "alma/availability" => "alma#availability"
  end


  # matches
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/articles", to: "primo_central#index", as: "search", via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<div id="footer">
  <div id="site-footer">
    <div class="row">
      <div class="col">

        <div class="postscript">

          <div class="region region-postscript-first">
            <div class="dept-address">
              <address><span class="place-title bebas">Temple University</span><br /><span class="place-location">University Libraries</span><br />1210 Pollet Walk<br />Philadelphia, PA 19122</address>
            </div>
           </div>

          <div class="region region-postscript-second">
            <nav role="navigation">
              <ul>
                <li><a href="https://directory.temple.edu/">Cherry and White Directory</a></li>
                <li><a href="http://temple.edu/maps-and-directions">Maps and Directions</a></li>
                <li><a href="http://temple.edu/contact">Contact</a></li>
              </ul>
            </nav>
          </div>

          <div class="region region-postscript-third">
            <nav role="navigation">
              <ul>
                <li style="display:inline;margin-right:14px;"><%= link_to image_tag('fb.png', class: 'social-icon', alt: 'Facebook Icon', :style => 'width:32px;height:32px;'), 'https://www.facebook.com/templelibraries/' %></li>
                <li style="display:inline;margin-right:14px;"><%= link_to image_tag('twitter.png', class: 'social-icon', alt: 'Twitter Icon', :style => 'width:36px;height:36px;margin-top:2px;'), 'https://twitter.com/TempleLibraries' %></li>
                <li style="display:inline"><%= link_to image_tag('instagram.png', class: 'social-icon', alt: 'Instagram Icon', :style => 'width:34px;height:34px;'), 'http://instagram.com/tulibraries' %></li>
              </ul>
              <br /><br />
            </nav>
          </div>
        </div>

        <div class="tu-links">
          <div class="region region-footer">
            <div>
              <ul>
                <li><a class="droid" href="http://tuportal.temple.edu/">TUportal</a></li>
                <li><a class="droid" href="http://tumail.temple.edu/">TUmail</a></li>
                <li><a class="droid" href="http://temple.edu/sitemap/">Sitemap</a></li>
                <li><a class="droid" href="http://temple.edu/about/temple-university-accessibility-statement/">Accessibility</a></li>
                <li><a class="droid" href="http://policies.temple.edu/">Policies</a></li>
                <li><a class="droid" href="http://temple.edu/hr/departments/employment/jobs_within.htm">Careers at Temple</a></li>
                <li><small>Copyright <%= Time.current.year %> Temple University | All Rights Reserved</small></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header_navbar.html.erb
<nav id="logo-navbar" class="navbar navbar-header bg-white align-items-center" role="navigation">
  <%= link_to library_link, class: "header-name d-flex align-items-center" do %>
    <%= image_tag("temple-logo-t-box.svg", class: "header-logo d-inline-flex", alt: "temple-logo") %>
    <span class="logo-text">University Libraries</span>
  <% end %>
</nav>

<nav id="red-navbar" class="navbar navbar-header navbar-expand-sm bg-red py-0" role="navigation">
  <div class="d-inline-flex pl-md-3 pr-md-1 w-100 flex-wrap align-items-center">
    <h1 class="col-sm-auto py-md-1">
      <%= link_to("Library Search", everything_path, id: "catalog-header") %>
    </h1>
    <div class="ml-auto col-sm-auto py-md-1">
      <%= render partial: "/user_util_links" %>
    </div>
  </div>
</nav>

<nav id="search-navbar" class="navbar navbar-default bg-tan border-bottom border-red" role="navigation">
  <div class="container mx-auto">
    <%= render_search_bar %>
  </div>
</nav>

<%= render "navbar" %>

app/views/shared/_nav_bar_login_links.html.erb
<% if current_user %>
    <li class="user-links">
      <%= link_to t('blacklight.header_links.logout'), destroy_user_session_path(type: session[:alma_auth_type]), :method => 'delete', id: "logout" %>
    </li>
<% else %>
    <li class="user-links">
      <%= link_to t('blacklight.header_links.login'), new_user_session_with_redirect_path(users_account_path), data: {"blacklight-modal": "trigger"}, id: "login" %>
    </li>
<% end %>