config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "search#index"

  # advanced forms
  match "journals/advanced", to: "journals_advanced#index", as: "journals_advanced_search", via: [:get, :post]
  match "databases/advanced", to: "databases_advanced#index", as: "databases_advanced_search", via: [:get, :post]
  match "articles/advanced", to: "primo_advanced#index", as: "articles_advanced_search", via: [:get, :post]
  match "catalog/advanced", to: "advanced#index", as: "advanced_search", via: [:get, :post]
  match "catalog/:id/purchase_order", to: "catalog#purchase_order_action", via: [:post], as: "purchase_order_action"

  # concerns
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  # mounts
  mount Blacklight::Engine => "/"
  mount BlacklightAdvancedSearch::Engine => "/"
  mount BentoSearch::Engine => "/bento"

  get "books/:id", to: redirect { |_, req| req.url.sub("books", "catalog") }
  get "books", to: redirect { |_, req|
    redirect_path = req.url.sub("books", "catalog")

    if req.params.empty?
      redirect_path += "?f[format][]=Book"
    elsif !req.params.dig("f", "format")&.include?("Book")
      redirect_path += "&f[format][]=Book"
    end

    redirect_path
  }


  # resource and resources
  resource :catalog, only: [:index], as: "catalog", path: "/catalog", controller: "catalog" do
    concerns :searchable
    concerns :range_searchable
  end

  resource :journals, only: [:index], as: "journals", path: "/journals", controller: "journals" do
    concerns :searchable
    concerns :range_searchable
  end

  resource :databases, only: [:index], as: "databases", path: "/databases", controller: "databases" do
    concerns :searchable
    concerns :range_searchable
  end

  resources :solr_documents, only: [:show], path: "/catalog", controller: "catalog" do
    concerns :exportable
  end

  resources :solr_journal_documents, only: [:show], path: "/journals", controller: "journals" do
    concerns :exportable
  end

  resources :solr_database_documents, only: [:show], path: "/databases", controller: "databases" do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete "clear"
    end
  end

  resources :primo_central_documents, only: [:show], path: "/articles", controller: "primo_central" do
    concerns :exportable
  end

  post "catalog/:id/track" => "catalog#track"
  post "articles/:id/track" => "primo_central#track", as: :track_primo_central
  post "journals/:id/track" => "journal#track"
  post "databases/:id/track" => "databases#track"

  devise_for :users, controllers: { sessions: "sessions", omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get "alma/social_login_callback" => "sessions#social_login_callback"
  end

  # auth
  authenticate do
    post "users/renew"

    get "users/account"

    get "users/fines", as: "user_fines"

    get "users/holds", as: "user_holds"

    get "users/loans", as: "user_loans"

    post "users/renew_selected"

    post "users/renew_all"

  end

  # gets
  get "bento" => "search#index", :as => "multi_search"
  get "everything" => "search#index", :as => "everything"
  get "catalog/:id/staff_view", to: "catalog#librarian_view", as: "staff_view"
  get "articles_advanced", to: "primo_advanced#index", as: "legacy_articles_advanced_search"

  get "catalog/:id/index_item", to: "catalog#index_item", as: "index_item"
  get "journals/:id/index_item", to: "journals#index_item", as: "journal_item"
  get "databases/:id/index_item", to: "databases#index_item", as: "database_item"
  get "articles/:id/index_item", to: "primo_central#index_item", as: "articles_index_item"
  get "catalog/:id/purchase_order", to: "catalog#purchase_order", as: "purchase_order"


  #
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  # we want helper methods for multi_search_path and multi_search_url
  # too, without removing root_url and root_path helpers. oddly, repeating
  # root seems to work.

  get "almaws/item/:mms_id", to:  "almaws#item", as: "item"
  get "almaws/request/:mms_id/:pickup_location/:request_level", to: "almaws#request_options", as: "request_options"
  post "almaws/request/digitization", to: "almaws#send_digitization_request", as: "digitization_request"
  post "almaws/request/hold", to: "almaws#send_hold_request", as: "hold_request"
  post "almaws/request/booking", to: "almaws#send_booking_request", as: "booking_request"

  scope module: "blacklight_alma" do
    get "alma/availability" => "alma#availability"
  end


  # matches
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/articles", to: "primo_central#index", as: "search", via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/helpers/catalog_helper.rb
# frozen_string_literal: true

module CatalogHelper
  include Blacklight::CatalogHelperBehavior
  include BlacklightAlma::CatalogOverride

  def thumbnail_classes(document)
    classes = %w[thumbnail col-sm-3 col-lg-2]
    document.fetch(:format, []).compact.each do |format|
      classes << "#{format.parameterize.downcase.underscore}_format"
    end
    classes.join " "
  end

  def isbn_data_attribute(document)
    values = document.fetch(:isbn_display, [])
    values = [values].flatten.map { |value|
      value.gsub(/\D/, "") if value
    }.compact.join(",")

    "data-isbn=#{values}" if !values.empty?
  end

  def lccn_data_attribute(document)
    values = document.fetch(:lccn_display, [])
    values = [values].flatten.map { |value|
      value.gsub(/\D/, "") if value
    }.compact.join(",")

    "data-lccn=#{values}" if !values.empty?
  end

  def default_cover_image(document)
    formats = document.fetch(:format, [])
    # In case we fetched the default value, or the format value was ""
    formats << "unknown" if formats.empty?
    format = formats.first.to_s.parameterize.underscore
    image = Rails.application.config.assets.default_cover_image
      .merge(
        "article" => "journal_periodical",
        "dissertation" => "script",
        "dissertation_thesis" => "script",
        "government_document" => "journal_periodical",
        "journal" => "journal_periodical",
        "legal_document" => "journal_periodical",
        "newspaper_article" => "journal_periodical",
        "other" => "unknown",
        "patent" => "journal_periodical",
        "reference_entry" => "journal_periodical",
        "research_dataset" => "dataset",
        "review" => "journal_periodical",
        "statistical_data_set" => "dataset",
        "technical_report" => "journal_periodical",
        "book_chapter" => "book",
        "text_resource" => "journal_periodical",
    ).fetch(format, "unknown")

    "svg/" + image + ".svg"
  end

  def separate_formats(response)
    document = response[:document]
    formats = %w[]
    document[:format].each do |format|
      format = h(format)
      css_class = format.to_s.parameterize.underscore
      formats << "<span class='#{css_class}'> #{format}</span>"
    end
    formats.join("<br />")
  end

  # Used to toggle the search bar form path.
  # Hack for Advanced search page
  def search_url_picker
    current_page?("/advanced") ? search_catalog_url : search_action_url
  end

  # Overridden because we want to use our merged @response["docs"] with docs
  # from solr and primo together.
  def current_bookmarks(response = nil)
    response ||= @response
    @current_bookmarks ||=
      current_or_guest_user
      .bookmarks_for_documents(@response["docs"] ||
    response.documents).to_a
  end

  ##
  # Overridden so that we can controll the number of pages from the controller.
  #
  # Look up the current per page value, or the default if none if set
  #
  # @return [Integer]
  def current_per_page
    (@response["rows"] if @response["rows"] && @response["rows"] > 0) ||
      (@response.rows if @response && @response.rows > 0) ||
      params.fetch(:per_page, default_per_page).to_i
  end

  def render_online_availability(doc_presenter)
    field = blacklight_config.show_fields["electronic_resource_display"]
    online_resources = [doc_presenter.field_value(field)]
      .select { |r| !r.empty? }.compact

    if !online_resources.empty?
      render "online_availability", online_resources: online_resources
    end
  end

  def render_online_availability_button(doc)
    links = check_for_full_http_link(document: doc, field: "electronic_resource_display")

    if !links.empty?
      render "online_availability_button", document: doc, links: links
    end
  end

  def render_bound_with_ids(document)
    if index_fields["bound_with_ids"] && document.alma_availability_mms_ids.present?
      content_tag :span, nil, class: "row document-metadata blacklight-availability availability-ajax-load", "data-availability-ids": document.alma_availability_mms_ids.join(",")
    end
  end

  ##
  # Overridden from module Blacklight::BlacklightHelperBehavior.
  #
  # Overridden in order to disable rel alternate links added to page headers.
  def render_link_rel_alternates(document = @document, options = {})
    ""
  end

  def advanced_catalog_search_path
    params = @search_state.to_h.select { |k, v| !["page"].include? k }
    blacklight_advanced_search_engine.advanced_search_path(params)
  end

  def render_availability(doc)
    if index_fields(doc).fetch("availability", nil)
      render "index_availability_section", document: doc
    end
  end

  def render_purchase_order_availability(presenter)
    doc = presenter.document
    return unless doc.purchase_order?


    field = presenter.send(:fields)["purchase_order_availability"]

    if field.with_panel
      rows = [ t("purchase_order_allowed") ]
      render partial: "availability_panel", locals: { label: field.label, rows: rows }

    elsif current_user && !current_user.can_purchase_order?
      content_tag :div, t("purchase_order_allowed"), class: "availability border border-tan-border"
    else
      render_purchase_order_button(document: doc, config: field)
    end
  end

  def render_purchase_order_button(args)
    return unless args[:document].purchase_order?

    doc = args[:document]
    with_po_link = args.dig(:config, :with_po_link)

    if !current_user
      link = with_po_link ? render_purchase_order_show_link(args) : ""
      render partial: "purchase_order_anonymous_button", locals: { link: link, document: doc }
    elsif current_user.can_purchase_order?
      label = content_tag :span, "Request Rapid Access", class: "avail-label"
      path = purchase_order_path(id: doc.id)
      link = link_to label, path, class: "btn btn-sm btn-danger", title: "Open a modal form to request a purchase for this item.", target: "_blank", id: "purchase_order_button-#{doc.id}", data: { "blacklight-modal": "trigger" }
      content_tag :div, link, class: "requests-container"
    end
  end

  def render_purchase_order_show_link(args = { document: @document })
    return unless args[:document].purchase_order?

    if !current_user
      id = args[:document].id
      link_to("Log in to access request form", doc_redirect_url(id), data: { "blacklight-modal": "trigger" })
    elsif current_user.can_purchase_order?
      render_purchase_order_button(args)
    end
  end

  def render_email_form_field
    if !current_user&.email
      render partial: "email_form_field"
    end
  end

  def library_link
    Rails.configuration.library_link
  end

  def grouped_citations(documents)
    Citation.grouped_citations(documents.map(&:citations))
  end

  def render_marc_view
    if @document.respond_to?(:to_marc)
      render "marc_view", document: @response.documents.first
    else
      t("blacklight.search.librarian_view.empty")
    end
  end

  def back_to_catalog_path
    search_catalog_path(search_params)
  end

  def back_to_journals_path
    search_journals_path(search_params)
  end

  def back_to_articles_path
    search_path(search_params)
  end

  def back_to_databases_path
    search_databases_path(search_params)
  end

  def get_search_params(field, query)
    case field
    when "title_uniform_display", "title_addl_display", "relation"
      { search_field: "title", q: query }
    else
      { search_field: field, q: query }
    end
  end

  def fielded_search(query, field)
    params = get_search_params(field, query)
    link_url = search_action_path(params)
    title = params[:title] || params[:q]
    link_to(title, link_url)
  end

  def list_with_links(args)
    args[:document][args[:field]].map { |field| content_tag(:li,  fielded_search(field, args[:field]), class: "list_items") }.join("").html_safe
  end

  def creator_index_separator(args)
    creator = args[:document][args[:field]]
    creator.map do |name|
      plain_text_subfields = name.gsub("|", " ")
      creator = plain_text_subfields
    end
    creator
  end

  def subject_links(args)
    args[:document][args[:field]].map do |subject|
      link_to(subject.sub("— — ", "— "), "#{base_path}?f[subject_facet][]=#{CGI.escape subject}")
    end
  end

  def genre_links(args)
    args[:document][args[:field]].map do |genre|
      link_to(genre, "#{search_catalog_path}?f[genre_full_facet][]=#{CGI.escape genre}")
    end
  end

  def database_type_links(args)
    args[:document][args[:field]].map do |type|
      link_to(type.sub("— — ", "— "), "#{base_path}?f[format][]=#{CGI.escape type}", class: "p-2")
    end
  end

  def has_one_electronic_resource?(document)
    document.fetch("electronic_resource_display", []).length == 1
  end

  def has_many_electronic_resources?(document)
    electronic_resources = document.fetch("electronic_resource_display", [])
    electronic_resources.length > 1 ||
      has_one_electronic_resource?(document) &&
      render_electronic_notes(electronic_resources.first).present?
  end

  def check_for_full_http_link(args)
    [args[:document][args[:field]]].flatten.compact.map { |field|
      if field["url"].present?
        electronic_access_links(field)
      else
        electronic_resource_link_builder(field)
      end
    }.join("").html_safe
  end

  def electronic_access_links(field)
    text = field.fetch("title", "Link to Resource").sub(/ *[ ,.\/;:] *\Z/, "")
    url = field["url"]
    content_tag(:div, link_to(text, url, title: "Target opens in new window", target: "_blank"), class: "electronic_links online-list-items online-card")
  end

  def electronic_resource_link_builder(field)
    return if field.empty?
    return if field["availability"] == "Not Available"

    title = field.fetch("title", "Find it online")
    electronic_notes = render_electronic_notes(field)

    item_html = [render_alma_eresource_link(field["portfolio_id"], title), field["subtitle"]]
      .select(&:present?).join(" - ")
    item_html = [item_html, electronic_notes]

app/views/catalog/_aeon_request.html.erb
<div class="aeon-wrapper">
  <%= aeon_request_button(document) %>
</div>

app/views/catalog/_constraints_element.html.erb
<%  # local params:
    # label
    # value
    # options =>
    #   :remove => url for a remove constraint link
    #   :classes => array of classes to add to container span
    options ||= {}
%>

<span class="<%= options[:classes].join(" ") if options[:classes] %> btn-group btn-block appliedFilter filter-group constraint">
  <span class="constraint-value btn btn-block btn-default btn-disabled">
    <% unless label.blank? %>
      <span class="filterName"><%= label %>
        <i class="fa fa-chevron-right filter-separator"></i>
      </span>
    <% end %>
    <% unless value.blank? %>
      <%= content_tag :span, value, class: 'filterValue' %>
    <% end %>
  </span>
  <% unless options[:remove].blank? %>
    <% accessible_remove_label = content_tag :span, class: 'sr-only' do
        if label.blank?
          t('blacklight.search.filters.remove.value', value: value)
        else
          t('blacklight.search.filters.remove.label_value', label: label, value: value)
        end
      end
    %>

    <%= link_to(content_tag(:span, '', class: 'remove-icon') + accessible_remove_label,
                options[:remove], class: 'btn btn-block remove remove-constraints mt-0 pt-2') %>
  <%- end -%>
</span>

app/views/catalog/_facet_pivot.html.erb
<% not_selected = !pivot_facet_in_params?(field_name, display_facet) %>
<ul <%=facet_value_id(display_facet)%> class="pivot-facet list-unstyled <%=initial_collapse(display_facet, not_selected)%>">
  <% display_facet.items.each do |item| %>
    <li>
    <span class="facet-values">
      <% unless item.items.blank?  %>
        <a class="far fa-plus-square text-dark"  href="<%='#'+item.field.parameterize+'-'+item.value.parameterize%>" data-target=<%='#'+item.field.parameterize+'-'+item.value.parameterize%> data-toggle="collapse"></a>
      <% end %>

    <% if facet_in_params?(field_name, item) %>
        <%= render_selected_facet_value(field_name, item) %>
      <% else %>
        <%= render_facet_value(field_name, item) %>
    <% end %>
    </span>

    <% unless item.items.blank? %>
      <%= render "facet_pivot", display_facet: item, field_name: field_name %>
    <% end %>
    </li>
  <% end %>

</ul>

app/views/catalog/_fields.html.erb
<% doc_presenter = index_presenter(document) %>

<dl class="row document-metadata mb-0">
<% index_fields(document).each do |field_name, field| -%>
  <% if should_render_index_field? document, field %>
    <% unless field[:no_label] %>
    <dt class="index-label col-sm-12 col-md-4 col-lg-3 blacklight-<%= field_name.parameterize %>"><%= render_index_field_label document, field: field_name %></dt>
    <dd class="col-sm-12 col-md-5 col-lg-7 blacklight-<%= field_name.parameterize %>">
    <% end %>
      <% if field[:raw] %>
        <%= raw doc_presenter.field_value(field) %>
      <% else %>
        <%= doc_presenter.field_value(field) %>
      <% end -%>
    </dd>
  <% end -%>
<% end -%>
</dl>

<%= render_bound_with_ids(document) %>

app/views/catalog/_index_default.html.erb
<% doc_presenter = index_presenter(document) %>

<div class="clearfix d-md-inline-flex flex-row-reverse w-100">
<%# default partial to display solr document fields in catalog index view %>
  <% unless controller_name == "databases" %>
    <div <%= isbn_data_attribute(document) %> class="book-info-srch thumbnail float-md-right pr-3">
      <%= link_to document do %>
        <%= image_tag "", :alt => "Book cover for " + document["title_statement_display"].to_s, :class => "book_cover invisible"  %>
        <%= image_tag default_cover_image(document), :class => "default", :alt => "default cover image" %>
      <% end %>
    </div>
  <% end %>
  <div class="book_info w-100">
    <%= render "fields", document: document, document_counter: document_counter %>
  </div>
</div>

<%= render_availability(document) %>

<hr class="document-divider" />

app/views/catalog/_physical_availability_card.html.erb
<%# This template is used for the initial load of availability information in the availability panel %>
<%# It gets replaced by a similar template in almaws/item.html.erb, so changes need to be in both places %>

<% @document_availability = document_availability_info(document) %>

<% unless @document_availability.all?(&:empty?) %>
  <% sort_order_for_holdings(@document_availability).each do |key, items| %>
    <div data-long-list class="m-0" data-controller="availability">
      <div class="d-lg-flex table-heading ml-0 mb-0 border-bottom border-top border-tan-border justify-content-lg-between avail-list">
        <div class="library-name card-title col-sm-12 col-md-4"><%= temporary_library_name_for_move(key, items) %></div>
        <div class="holdings-summary col-sm-12 col-md-4"><%= summary_list(items) %></div>
        <div class="aeon-request col-sm-12 col-md-4"><%= aeon_request_button(document, key) %></div>
      </div>

      <% items.each do |item| %>
        <div class="item-info row avail-info-rows border-bottom border-tan-border m-0">
          <div class="col-sm-12 col-md-2"><strong><%= location_status(item) %></strong></div>
          <div class="col-sm-12 col-md-2"><%= alternative_call_number(item) %></div>
          <div class="col-sm-12 col-md-5">
            <span><%= description(item) %></span>
            <span><%= public_note(item) %></span>
            <span><%= material_type(item) %></span>
          </div>
          <div class="spinner">
            <span class="fa fa-spinner" role="spinbutton"></span>
            <span>Loading Availability</span>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

<% else %>
  <div id="error-message">We are unable to find availability information for this record. Please contact the library for more information.</div>
<% end %>

app/views/catalog/_search_form.html.erb
<%= form_tag search_action_url, method: :get, class: "search-query-form col-lg-9 col-sm-12", role: "search", id: "catalog-search" do %>
  <%= render_hash_as_hidden_fields(search_state.params_for_search.except(:q, :search_field, :qt, :page, :utf8)) %>

    <% if search_fields.length > 1 %>
      <label for="search_field" class="sr-only"><%= t("blacklight.search.form.search_field.label") %></label>
    <% end %>

    <div class="input-group d-flex">
      <% if search_fields.length > 1 %>
        <%= select_tag(:search_field, options_for_select(search_fields, h(search_params[:search_field])), title: t("blacklight.search.form.search_field.title"), id: "search_field", class: " custom-select search-field flex-shrink-1") %>
      <% elsif search_fields.length == 1 %>
        <%= hidden_field_tag :search_field, search_fields.first.last %>
      <% end %>

    <label for="q" class="sr-only"><%= t("blacklight.search.form.search.label") %></label>
    <%= text_field_tag :q, search_params[:q], placeholder: t("blacklight.search.form.search.placeholder"), class: "search_q q form-control w-50", id: "q", autofocus: presenter.autofocus?, data: { autocomplete_enabled: autocomplete_enabled? }  %>

    <span class="input-group-append">
      <button type="submit" class="btn btn-red search-btn" id="search" aria-label="search">
        <i class="fa fa-search"></i>
    </button>
    </span>
  </div>
<% end %>

<div class="mx-auto">
  <%= render "advanced_search_link" %>
</div>

app/views/catalog/_search_header.html.erb
<%= render 'did_you_mean' %>

<div class="sort-per-page-container border-bottom border-light-grey p-3 mb-3">
  <%= render 'sort_and_per_page' %>
</div>

app/views/catalog/_show_availability.html.erb
<% doc_presenter = show_presenter(document) %>
<%# partial to display availability details in catalog show view -%>

<% @response["response"][:docs].each_with_index do |field, i| %>
  <% if document["availability_facet"][i] == "Online" %>
    <% document_show_fields(document).each do |field_name, field| %>
    <% if field_name == 'electronic_resource_display' %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><dt class="blacklight-<%= field_name.parameterize %>"><%= render_document_show_field_label document, field: field_name %></dt></h3>
        </div>
        <div class="panel-body">
          <dd class="blacklight-<%= field_name.parameterize %>">
            <ul>
            <% doc_presenter.configuration.show_fields.fetch(field_name)[:helper_method] %>
              <% values = Array.wrap(doc_presenter.field_value field_name) %>
              <% values.each do |value| %>
              <li class="list_items"> <%= safe_join(Array.wrap(value)) %> </li>
            </ul>
          </dd>
        </div>
      </div>
      <% end %>
    <% end %>
  <% end %>
  <% elsif document["availability_facet"][i] == "At the Library" %>
    <div class="availability_iframe panel panel-default">
      <h4 class="panel-heading">Availability</h4>
      <iframe class="bl_alma_iframe" src="<%= alma_app_fulfillment_url(document) %>"></iframe>
    </div>
  <% end %>
<% end %>

app/views/catalog/_show_tools.html.erb
<%-
  # Compare with render_document_functions_partial helper, and
  # _document_functions partial. BL actually has two groups
  # of document-related tools. "document functions" by default
  # contains Bookmark functionality shown on both results and
  # item view. While "document tools" contains external export type
  # functions by default only on detail.

-%>
<% if show_doc_actions? %>
<% @sendto = {} %>
      <ul id="tools-navbar">
        <%= render_show_doc_actions @document do |config, inner| %>
            <!-- Temporarily remove bookmark feature for articles (BL-912) -->
          <% if config.key == :bookmark %>
            <li class="<%= config.key %>" id="bookmark_button">
              <%= inner %>
            </li>
            <% if @document.citable? %>
            <li>
              <%= link_to t("blacklight.tools.cite_html"), citation_solr_document_path(:id => @document), {:id => "citeLink", :data => {:blacklight_modal => "trigger"}, :class => "citation btn btn-sm"} %>
            </li>
            <% end %>
          <% else %>

            <% @sendto[config.key] = inner %>

          <% end %>
        <% end %>

        <li id="sendto-menu">
          <div id="sendto" class="dropdown show">
            <button class="btn btn-sm dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Send To <span class="caret"></span></button>
            <div class="sendto-menu dropdown-menu bg-white border border-light-grey">
              <% @sendto.each do |key,value| %>
                <div class="sendto-item dropdown-item">
                  <%= value %>
                </div>
              <% end %>
            </div>
          </div>
        </li>
      </ul>
<% end %>

app/views/catalog/_show_tools_navbar.html.erb
<%= render :partial => 'show_tools' %>
  
<% unless @document.more_like_this.empty? %>
  <div class="panel panel-default">
    <div class="panel-heading">More Like This</div>
    <div class="panel-body">
      <%= render :collection => @document.more_like_this, :partial => 'show_more_like_this', :as => :document %>
    </div>
  </div>
<% end %>

app/views/catalog/_sort_and_per_page.html.erb
<div id="sortAndPerPage" class="sort-pagination d-flex flex-wrap align-items-start">
  <%= render partial: "paginate_compact", object: @response if show_pagination? %>
  <%= render_results_collection_tools wrapping_class: "search-widgets" %>
</div>

app/views/catalog/_staff_view_link.html.erb
  <div id="stafflink" class="ml-3">
    <%= link_to t("blacklight.search.librarian_view.title"), staff_view_path %>
  </div>

app/views/catalog/librarian_view.html.erb
<div class="modal-header d-flex align-items-center">
  <h3 class="modal-title librarian-header"><%= t('blacklight.search.librarian_view.title') %></h3>
  <%= link_to t("blacklight.search.back"), "../#{@document.id}"%>
</div>

<%= render_marc_view %>